"""
Trace the chameleon mark into polygon shapes (outline + holes) for 3D extrusion.

Input : assets/source/Camaleonte_nero.png  (RGBA silhouette)
Output: lib/chameleon-shape.ts             (committed; the build does NOT need cv2)

The TS export is consumed by components/hero/Chameleon.tsx to build a
THREE.ExtrudeGeometry. Re-run only if the mark changes:

    python3 scripts/trace_chameleon.py
"""
import cv2
import numpy as np
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "source", "Camaleonte_nero.png")
OUT = os.path.join(ROOT, "lib", "chameleon-shape.ts")

img = cv2.imread(SRC, cv2.IMREAD_UNCHANGED)  # BGRA
h, w = img.shape[:2]
alpha = img[:, :, 3]
mask = (alpha > 128).astype(np.uint8) * 255

contours, hierarchy = cv2.findContours(mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)
hierarchy = hierarchy[0]
img_area = float(w * h)

# Group outers with their holes (RETR_CCOMP => 2 levels).
shapes = {}  # idx -> {"outer": cnt, "holes": [cnt,...]}
for i, cnt in enumerate(contours):
    parent = hierarchy[i][3]
    if parent == -1:
        shapes.setdefault(i, {"outer": cnt, "holes": []})
for i, cnt in enumerate(contours):
    parent = hierarchy[i][3]
    if parent != -1 and parent in shapes:
        shapes[parent]["holes"].append(cnt)


def simplify(cnt, frac):
    eps = frac * cv2.arcLength(cnt, True)
    return cv2.approxPolyDP(cnt, eps, True).reshape(-1, 2)


kept = []
for idx, grp in shapes.items():
    if cv2.contourArea(grp["outer"]) < 0.003 * img_area:
        continue
    outer = simplify(grp["outer"], 0.0009)
    holes = []
    for hcnt in grp["holes"]:
        if cv2.contourArea(hcnt) < 0.0006 * img_area:
            continue
        holes.append(simplify(hcnt, 0.0022))
    kept.append({"outline": outer, "holes": holes})

# Sort by outer area desc (body first).
kept.sort(key=lambda s: cv2.contourArea(s["outline"].reshape(-1, 1, 2).astype(np.int32)), reverse=True)

# Normalize: center on origin, scale longest side to 2.0, flip Y (image is y-down).
allpts = np.vstack([s["outline"] for s in kept] + [hh for s in kept for hh in s["holes"]])
minx, miny = allpts.min(axis=0)
maxx, maxy = allpts.max(axis=0)
cx, cy = (minx + maxx) / 2.0, (miny + maxy) / 2.0
span = max(maxx - minx, maxy - miny)
s = 2.0 / span
aspect = (maxx - minx) / (maxy - miny)


def norm(pts):
    out = []
    for x, y in pts:
        out.append([round(float((x - cx) * s), 3), round(float(-(y - cy) * s), 3)])
    return out


def fmt_ring(pts):
    return "[" + ",".join(f"[{x},{y}]" for x, y in pts) + "]"


lines = []
lines.append("// AUTO-GENERATED by scripts/trace_chameleon.py — do not edit by hand.")
lines.append("// Traced from assets/source/Camaleonte_nero.png for 3D extrusion.")
lines.append("export interface ChameleonShape {")
lines.append("  outline: [number, number][];")
lines.append("  holes: [number, number][][];")
lines.append("}")
lines.append(f"export const CHAMELEON_ASPECT = {round(aspect, 4)};")
lines.append("export const CHAMELEON_SHAPES: ChameleonShape[] = [")
total_pts = 0
for sgrp in kept:
    o = norm(sgrp["outline"])
    total_pts += len(o)
    hs = [norm(hh) for hh in sgrp["holes"]]
    total_pts += sum(len(x) for x in hs)
    holes_str = "[" + ",".join(fmt_ring(hh) for hh in hs) + "]"
    lines.append(f"  {{ outline: {fmt_ring(o)}, holes: {holes_str} }},")
lines.append("];")
lines.append("")

with open(OUT, "w") as f:
    f.write("\n".join(lines))

print(f"shapes={len(kept)}  total_points={total_pts}  aspect={aspect:.3f}")
for i, sgrp in enumerate(kept):
    print(f"  shape{i}: outline={len(sgrp['outline'])} holes={[len(hh) for hh in sgrp['holes']]}")
print("wrote", os.path.relpath(OUT, ROOT))
